#!/usr/bin/env python3
"""
Ultron LinkedIn Content Engine - Main Entrypoint
Complete pipeline: design system → variant generation → scoring → export → database sync
"""

import asyncio
import sys
import json
from pathlib import Path
import os

# Add scripts dir to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from batch_generator import generate_and_save, VariantGenerator
from design_system import DESIGN_COLORS, DESIGN_RULES
from export_playwright import PlaywrightExporter
from scoring import BrewAlgorithm, format_score_report
from db_sync import SupabaseSync


def print_header(text: str):
    """Print formatted header"""
    print(f"\n{'='*80}")
    print(f"{text}")
    print(f"{'='*80}\n")


def test_design_system():
    """Test design system module"""
    print_header("🎨 DESIGN SYSTEM")
    
    print(f"Colors loaded: {len(DESIGN_COLORS)}")
    for name, color in list(DESIGN_COLORS.items())[:5]:
        print(f"  {name}: {color}")
    print(f"  ... and {len(DESIGN_COLORS) - 5} more")
    
    print(f"\nDesign rules: {len(DESIGN_RULES)}")
    print(f"  Max card border-radius: {DESIGN_RULES['borders']['max_card_radius']}")
    print(f"  Section padding: {DESIGN_RULES['spacing']['section_padding_top']} / {DESIGN_RULES['spacing']['section_padding_bottom']}")
    
    return True


def test_export_pipeline():
    """Test Playwright export pipeline"""
    print_header("🎬 EXPORT PIPELINE")
    
    html = """<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        * { margin: 0; padding: 0; }
        body {
            width: 1080px;
            height: 1350px;
            background: #F8F6F1;
            font-family: Arial, sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            padding: 40px;
            box-sizing: border-box;
        }
        h1 { color: #111; font-size: 48px; margin-bottom: 20px; font-weight: 900; }
        p { color: #888; font-size: 16px; line-height: 1.5; max-width: 600px; text-align: center; }
        footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            background: #111;
            padding: 16px 40px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            color: white;
            font-size: 13px;
        }
        footer span:last-child { color: #C84623; font-weight: 700; }
    </style>
</head>
<body>
    <h1>Pipeline Test</h1>
    <p>This is a test artifact generated by the Ultron LinkedIn Content Engine</p>
    <footer>
        <span>Ultron runs Claude with your context already loaded. No setup, no repeating yourself.</span>
        <span>See how at 51ultron.com -></span>
    </footer>
</body>
</html>"""
    
    exporter = PlaywrightExporter()
    result = exporter.export_sync(html, filename="pipeline-test")
    
    if result.get('success'):
        print(f"✓ PNG Export successful")
        print(f"  File: {result['png_filename']}")
        print(f"  Size: {result['file_size_kb']}KB")
        print(f"  Path: {result['png_path']}")
        return True
    else:
        print(f"✗ PNG Export failed: {result.get('error')}")
        return False


def test_scoring():
    """Test 360Brew scoring algorithm"""
    print_header("📊 SCORING ALGORITHM (360BREW)")
    
    brew = BrewAlgorithm()
    
    # High-scoring example
    result = brew.full_score(
        scroll_stop=85,
        clarity_3s=90,
        novelty=80,
        emotional_trigger=85,
        format_fit=90,
        utility_density=85,
        reusability=85,
        compression=80,
        structure_clarity=85,
        actionability=85,
        hierarchy_strength=85,
        contrast_control=80,
        spacing_balance=85,
        consistency=85,
        noise_level=80,
        framework_clarity=80,
        modularity=85,
        transferability=85,
        depth_vs_simplicity=80
    )
    
    print(format_score_report(result))
    return result.go_rebuild == 'GO'


def test_supabase_connection():
    """Test Supabase connection"""
    print_header("🗄️  SUPABASE CONNECTION")
    
    sync = SupabaseSync()
    
    if not sync.client:
        print("⚠ Supabase not configured (SUPABASE_URL and SUPABASE_KEY required)")
        return False
    
    # Try to fetch recent variants
    variants = sync.get_recent_variants(limit=3)
    
    if variants is not None:
        print(f"✓ Connection successful")
        print(f"  Recent variants: {len(variants)}")
        if variants:
            print(f"  Latest: {variants[0].get('concept', 'N/A')}")
        return True
    else:
        print(f"✗ Connection failed")
        return False


async def test_batch_generation(concept: str = "Claude vs ChatGPT vs Gemini for founders"):
    """Test full batch generation pipeline"""
    print_header("🚀 BATCH GENERATION PIPELINE")
    
    print(f"Concept: {concept}")
    print(f"Generating 5 variants...\n")
    
    try:
        result = await generate_and_save(
            concept=concept,
            num_variants=5,
            save_to_db=True
        )
        
        print(f"\n✓ Batch generation successful")
        return True
    
    except Exception as e:
        print(f"\n✗ Batch generation failed: {str(e)}")
        import traceback
        traceback.print_exc()
        return False


async def run_tests():
    """Run all tests"""
    print("\n")
    print("╔════════════════════════════════════════════════════════════════════════════════╗")
    print("║         ULTRON LINKEDIN CONTENT ENGINE - INITIALIZATION TEST SUITE             ║")
    print("╚════════════════════════════════════════════════════════════════════════════════╝")
    
    results = {}
    
    # Test 1: Design system
    results['design_system'] = test_design_system()
    
    # Test 2: Export pipeline
    print("Testing Playwright export (this may take 10-15 seconds)...")
    results['export_pipeline'] = test_export_pipeline()
    
    # Test 3: Scoring
    results['scoring'] = test_scoring()
    
    # Test 4: Supabase
    results['supabase'] = test_supabase_connection()
    
    # Summary
    print_header("📋 TEST SUMMARY")
    
    passed = sum(1 for v in results.values() if v)
    total = len(results)
    
    for test, result in results.items():
        status = "✓ PASS" if result else "✗ FAIL"
        print(f"{status}: {test}")
    
    print(f"\n{passed}/{total} tests passed")
    
    if passed == total:
        print("\n✓ All systems ready for batch generation!")
        print("\nTo generate variants, run:")
        print("  python main.py --generate 'Your concept here'")
    
    return passed == total


async def main():
    """Main entry point"""
    
    if len(sys.argv) < 2:
        # Run tests if no arguments
        await run_tests()
    elif sys.argv[1] == '--generate':
        # Generate variants
        if len(sys.argv) < 3:
            print("Usage: python main.py --generate 'Your concept here'")
            sys.exit(1)
        
        concept = ' '.join(sys.argv[2:])
        await test_batch_generation(concept)
    elif sys.argv[1] == '--help':
        print("""
Ultron LinkedIn Content Engine

Usage:
  python main.py              Run initialization tests
  python main.py --generate "Concept"  Generate 5 variants
  python main.py --help       Show this help

Environment variables required:
  SUPABASE_URL        - Your Supabase project URL
  SUPABASE_KEY        - Your Supabase API key
  ANTHROPIC_API_KEY   - Your Anthropic API key (auto-loaded in Claude Code)
        """)
    else:
        print(f"Unknown command: {sys.argv[1]}")
        print("Run: python main.py --help")


if __name__ == '__main__':
    asyncio.run(main())
